### ISSUE TITLE
Browser side provider hijack

### ISSUE THREAD

**Issue by pedro2555** [samthecodingman/signin-button#2]
Just a quick question that rose to mind, is there anything preventing me from altering the HTML and forcing a different provider (in Chrome Dev Tools for example)?

**Comment by samthecodingman** [comment]
Currently, no. These are just themed buttons to Google's spec. There is no sign-in logic as part of these elements.

To use them, you hook into the `on-tap` event and handle the sign-in flow yourself. So even if a user were to change the `provider`, it would just change the look of the button and any clicks/taps on that button would sign in using the logic you implement. You could argue that `provider` should be renamed `theme`, but this is done to align with the terminology used by sign-in libraries such as Firebase and their `polymerfire` elements.

Example:
`<signin-button provider="google" on-tap="_signinGoogle"></signin-button>` would produce a Google themed button and sign you in to Google on a tap.

`<signin-button provider="facebook" on-tap="_signinGoogle"></signin-button>` would produce a Facebook themed button but would still sign you into Google.

Pretty much any site is vulnerable to scripting attacks from the dev tools panel as it's considered a trusted scripting source (see "Self-XSS"). For these elements XSS mitigation is largely handled by the Polymer library that it depends on.

**Comment by pedro2555** [comment]
Yep, makes sense. Guess I overlooked a bit, and yes `provider` is better named `theme`. Or better yet:
```
<signin-button theme="{{provider}}" on-tap="_signin([[provider]])"></signin-button>
```

Anyway, seems fair; closing.
